name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '23'

    - name: Clone private configuration repository
      run: |
        git clone https://YahyaBekirCanevi:${{ secrets.PAT_TOKEN }}@github.com/YahyaBekirCanevi/stock.manage.config.git config-repo
      env:
        GIT_TERMINAL_PROMPT: 0

    - name: Create resources directory if not exists
      run: mkdir -p src/main/resources
      
    - name: Copy application.yml to project
      run: |
        cp config-repo/application-stock-manage.yml src/main/resources/application.yml

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Build and Run Tests
      run: ./gradlew build

    # Docker build and push
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/stock-manage-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stock-manage-app:latest

    # - name: Deploy Application
    #   run: |
    #     java -jar build/libs/stock.manage-0.0.1-SNAPSHOT.jar
